query postsConnection($where: PostWhereInput, $skip: Int, $take: Int = 10) {
  postsCount(where: $where)
  posts(where: $where, skip: $skip, take: $take) {
    ...PostNoNesting
    CreatedBy {
      ...UserNoNesting
    }
  }
}

query post($where: PostWhereUniqueInput!) {
  object: post(where: $where) {
    ...Post_
  }
}

mutation createPost($data: PostCreateInput!) {
  response: createPost(data: $data) {
    ...Post_
  }
}

mutation updatePost(
  $data: PostUpdateDataInput!
  $where: PostWhereUniqueInput!
) {
  response: updatePost(data: $data, where: $where) {
    ...Post_
  }
}

fragment PostNoNesting on Post {
  id
  createdAt
  updatedAt
  image
  status
  revision
  title
  description
  intro
  createdById
}

fragment Post_ on Post {
  ...PostNoNesting
  content
  CreatedBy {
    ...UserNoNesting
  }
}
